"""VerificationEngine — Bayesian multi-signal hallucination detector.

Implements the tiered architecture from Section 7.2 of the agentguard research:

  Tool Call Generated by Agent
           ↓
  [Tier 0: Zero-Cost Pre-Checks]
    Schema validation, latency plausibility, pattern matching, length bounds
           ↓
  [Bayesian Signal Combiner]
    Prior P(H) from tool's historical base rate
    Tier 0 signals update the posterior
           ↓
  [Decision: Proceed / Escalate]
    P(H) < 0.2 → accept
    0.2 ≤ P(H) < 0.5 → execute + Tier 1 post-check
    P(H) ≥ 0.5 → block or require confirmation
           ↓
  [Tier 1: Post-Tool Checks (Zero-Cost)]
    SPC baseline, session consistency, cross-call consistency
           ↓
  [Bayesian Update from Post-Tool Signals]
           ↓
  [Final Decision: accept / flag / block]

References:
- Section 4.2: Bayesian Multi-Signal Fusion with log-odds form
- Section 7.2: Recommended Architecture for AgentGuard Core
- Section 7.4: Novel Contributions (latency-as-proof, cross-session consistency)
"""

from __future__ import annotations

import threading

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from agentguard.verification.adaptive import AdaptiveThresholdManager
from agentguard.verification.baselines import ToolBaseline
from agentguard.verification.consistency import ConsistencyTracker
from agentguard.verification.signals import (
    check_latency_anomaly,
    check_response_length,
    check_response_patterns,
    check_schema_compliance,
    check_value_plausibility,
)


# ---------------------------------------------------------------------------
# Per-signal likelihood ratios (calibrated from literature, Section 4.2)
# ---------------------------------------------------------------------------

GLOBAL_LIKELIHOOD_RATIOS: dict[str, float] = {
    # Signal name → P(signal=1 | hallucination) / P(signal=1 | not hallucination)
    "schema_mismatch": 12.0,          # Very strong signal — LR ~12 from empirical data
    "latency_anomaly": 3.5,           # Medium signal — LR ~3.5
    "pattern_mismatch": 6.0,          # Strong signal — LR ~6
    "length_anomaly": 2.0,            # Weak signal — LR ~2
    "spc_anomaly": 3.0,               # Medium signal — LR ~3
    "session_inconsistency": 4.0,     # Medium-strong — LR ~4
    "historical_inconsistency": 4.5,  # Medium-strong — LR ~4.5
    "value_plausibility": 3.0,        # Medium signal
    "semantic_similarity_low": 4.0,   # Medium-strong (only when embeddings available)
}


# ---------------------------------------------------------------------------
# Supporting dataclasses
# ---------------------------------------------------------------------------


@dataclass
class SignalResult:
    """Result from a single verification signal."""

    fired: bool
    """True if the signal indicates hallucination evidence."""

    score: float
    """Strength of the evidence in [0.0, 1.0]."""

    detail: str
    """Human-readable explanation."""

    likelihood_ratio: float = 1.0
    """LR used in Bayesian update for this signal."""


class VerificationTier(int, Enum):
    """Which verification tier was needed to reach the final verdict."""
    TIER_0 = 0  # Zero-cost pre-checks only
    TIER_1 = 1  # Post-execution checks added
    TIER_2 = 2  # Escalated (reserved for future extension)


@dataclass
class VerificationResult:
    """Result from the VerificationEngine.

    Attributes:
        verdict: ``"accept"`` | ``"flag"`` | ``"block"``
        confidence: P(hallucination) in [0.0, 1.0]
        signals: Per-signal details keyed by signal name
        tier_reached: Which tier was needed
        explanation: Human-readable summary
        prior: Prior P(hallucination) used
        posterior: Posterior P(hallucination) after all signals
    """

    verdict: str
    confidence: float
    signals: dict[str, SignalResult]
    tier_reached: VerificationTier
    explanation: str
    prior: float
    posterior: float

    # Convenience accessors for backward compat with HallucinationResult
    @property
    def is_hallucinated(self) -> bool:
        """True when verdict is 'block'."""
        return self.verdict == "block"

    @property
    def reason(self) -> str:
        """Alias for explanation."""
        return self.explanation


@dataclass
class ToolProfile:
    """Expected behaviour profile for a single tool (mirrors old ToolProfile).

    Attributes:
        tool_name: Registered name of the tool.
        expected_latency_ms: ``(min_ms, max_ms)`` plausible latency range.
        required_fields: Fields that must appear in real responses.
        forbidden_fields: Fields that must not appear in real responses.
        response_patterns: Regexes that should match real responses.
        min_response_length: Minimum JSON-serialised response length.
        max_response_length: Maximum JSON-serialised response length.
        has_network_io: Whether the tool makes network calls (tightens latency check).
    """

    tool_name: str
    expected_latency_ms: tuple[float, float] = (50.0, 30_000.0)
    required_fields: list[str] = field(default_factory=list)
    forbidden_fields: list[str] = field(default_factory=list)
    response_patterns: list[str] = field(default_factory=list)
    min_response_length: Optional[int] = None
    max_response_length: Optional[int] = None
    has_network_io: bool = True  # Default: assume network I/O required


# ---------------------------------------------------------------------------
# VerificationEngine
# ---------------------------------------------------------------------------


class VerificationEngine:
    """Bayesian multi-signal verification engine for tool call outputs.

    This is the brain of the agentguard detection pipeline. It implements:

    1. Tier 0 zero-cost checks (schema, latency, patterns, length).
    2. Bayesian signal combiner using log-odds form for numerical stability.
    3. Tier 1 zero-cost post-execution checks (SPC baselines, session
       consistency, cross-session consistency).
    4. Adaptive thresholds that learn per-tool from user feedback.

    Args:
        prior: Default P(hallucination) prior (0.15 from empirical literature).
        accept_threshold: P(H) below this → accept.
        flag_threshold: P(H) above this → block (between → flag).
    """

    DEFAULT_PRIOR = 0.15

    def __init__(
        self,
        prior: float = DEFAULT_PRIOR,
        accept_threshold: float = 0.2,
        flag_threshold: float = 0.5,
    ) -> None:
        self.prior = prior
        self.accept_threshold = accept_threshold
        self.flag_threshold = flag_threshold

        self._engine_lock = threading.Lock()
        self._profiles: dict[str, ToolProfile] = {}
        self._baselines: dict[str, ToolBaseline] = {}
        self._consistency_tracker = ConsistencyTracker()
        self._threshold_manager = AdaptiveThresholdManager(
            global_threshold=flag_threshold
        )

    # ------------------------------------------------------------------
    # Registration
    # ------------------------------------------------------------------

    def register_tool_profile(
        self,
        tool_name: str,
        *,
        expected_latency_ms: tuple[float, float] = (50.0, 30_000.0),
        required_fields: Optional[list[str]] = None,
        forbidden_fields: Optional[list[str]] = None,
        response_patterns: Optional[list[str]] = None,
        min_response_length: Optional[int] = None,
        max_response_length: Optional[int] = None,
        has_network_io: bool = True,
    ) -> "VerificationEngine":
        """Register an expected-behaviour profile for a tool.

        Args:
            tool_name: Name of the tool to profile.
            expected_latency_ms: ``(min_ms, max_ms)`` plausible latency.
            required_fields: Keys that must appear in real responses.
            forbidden_fields: Keys that must not appear in real responses.
            response_patterns: Regexes that must match real responses.
            min_response_length: Minimum serialised length.
            max_response_length: Maximum serialised length.
            has_network_io: True if the tool makes network/IO calls.

        Returns:
            Self for method chaining.
        """
        self._profiles[tool_name] = ToolProfile(
            tool_name=tool_name,
            expected_latency_ms=expected_latency_ms,
            required_fields=required_fields or [],
            forbidden_fields=forbidden_fields or [],
            response_patterns=response_patterns or [],
            min_response_length=min_response_length,
            max_response_length=max_response_length,
            has_network_io=has_network_io,
        )
        return self

    # Keep old name for backward compatibility
    def register_tool(
        self,
        tool_name: str,
        *,
        expected_latency_ms: tuple[float, float] = (50.0, 30_000.0),
        required_fields: Optional[list[str]] = None,
        forbidden_fields: Optional[list[str]] = None,
        response_patterns: Optional[list[str]] = None,
        min_response_length: Optional[int] = None,
        max_response_length: Optional[int] = None,
        has_network_io: bool = True,
        **kwargs,
    ) -> "VerificationEngine":
        """Alias for :meth:`register_tool_profile` (backward compatibility)."""
        return self.register_tool_profile(
            tool_name,
            expected_latency_ms=expected_latency_ms,
            required_fields=required_fields,
            forbidden_fields=forbidden_fields,
            response_patterns=response_patterns,
            min_response_length=min_response_length,
            max_response_length=max_response_length,
            has_network_io=has_network_io,
        )

    def unregister_tool(self, tool_name: str) -> None:
        """Remove a tool profile and its baselines."""
        self._profiles.pop(tool_name, None)
        self._baselines.pop(tool_name, None)

    # ------------------------------------------------------------------
    # Calibration API — let users tune detection sensitivity
    # ------------------------------------------------------------------

    def calibrate(
        self,
        tool_name: Optional[str] = None,
        *,
        accept_threshold: Optional[float] = None,
        block_threshold: Optional[float] = None,
        prior: Optional[float] = None,
        likelihood_ratios: Optional[dict[str, float]] = None,
    ) -> "VerificationEngine":
        """Calibrate detection sensitivity for a specific tool or globally.

        This is the primary API for users to tune agentguard's sensitivity to
        match their deployment environment. Start with defaults, then calibrate
        based on observed false-positive/negative rates.

        Args:
            tool_name: Tool to calibrate. ``None`` for global settings.
            accept_threshold: P(H) below this → auto-accept (default 0.2).
                Lower = stricter (more flagging). Higher = more lenient.
            block_threshold: P(H) above this → auto-block (default 0.5).
                Lower = stricter (more blocking). Higher = more lenient.
            prior: Base probability of hallucination (default 0.15).
                Increase for tools that hallucinate often.
            likelihood_ratios: Per-signal likelihood ratios.
                Keys: ``"latency_anomaly"``, ``"schema_mismatch"``,
                ``"pattern_mismatch"``, ``"length_anomaly"``,
                ``"spc_anomaly"``, ``"session_inconsistency"``,
                ``"cross_session_anomaly"``.
                Higher values = signal is more indicative of hallucination.

        Returns:
            Self for method chaining.

        Example::

            engine = VerificationEngine()

            # Make a specific tool more sensitive (catches more hallucinations)
            engine.calibrate("search_web",
                accept_threshold=0.1,   # Stricter acceptance
                block_threshold=0.3,    # Lower blocking threshold
                prior=0.25,             # Higher base hallucination rate
            )

            # Make a tool more lenient (fewer false positives)
            engine.calibrate("get_time",
                accept_threshold=0.4,
                block_threshold=0.8,
                prior=0.05,
            )

            # Tune a specific signal globally
            engine.calibrate(likelihood_ratios={
                "schema_mismatch": 20.0,   # Make schema violations more damning
                "latency_anomaly": 5.0,    # Reduce weight of latency signal
            })
        """
        with self._engine_lock:
            if accept_threshold is not None:
                self.accept_threshold = accept_threshold
            if block_threshold is not None:
                self.flag_threshold = block_threshold
                self._threshold_manager.global_threshold = block_threshold

            if tool_name and prior is not None:
                # Set per-tool prior by recording synthetic feedback
                # This overrides the default 0.15 for this tool
                stats = self._threshold_manager._stats.get(tool_name)
                if stats is None:
                    from agentguard.verification.adaptive import ThresholdStats
                    self._threshold_manager._stats[tool_name] = ThresholdStats(
                        tool_name=tool_name,
                        threshold=self._threshold_manager.global_threshold,
                        ema_hallucination_rate=prior,
                        total_feedback=10,  # Enough to override the default
                    )
                else:
                    stats.ema_hallucination_rate = prior

            if likelihood_ratios:
                for signal_name, lr in likelihood_ratios.items():
                    if tool_name:
                        self._threshold_manager.update_likelihood_ratio(
                            tool_name, signal_name,
                            fired_hallucinated=lr,
                            fired_not_hallucinated=1.0,
                        )
                    else:
                        # Update global default LRs
                        from agentguard.verification.adaptive import DEFAULT_LIKELIHOOD_RATIOS
                        if hasattr(self._threshold_manager, '_likelihood_ratios'):
                            self._threshold_manager._likelihood_ratios['__global__'][signal_name] = lr

        return self

    def get_calibration(self, tool_name: Optional[str] = None) -> dict:
        """Return the current calibration settings.

        Args:
            tool_name: Tool to inspect. ``None`` for global settings.

        Returns:
            Dict with ``accept_threshold``, ``block_threshold``,
            ``prior``, ``likelihood_ratios``.
        """
        result = {
            "accept_threshold": self.accept_threshold,
            "block_threshold": self.flag_threshold,
            "prior": self._threshold_manager.get_prior(tool_name) if tool_name else 0.15,
        }
        if tool_name:
            result["tool_name"] = tool_name
            stats = self._threshold_manager._stats.get(tool_name)
            if stats:
                result["tool_threshold"] = stats.threshold
                result["hallucination_rate"] = stats.ema_hallucination_rate
                result["total_feedback"] = stats.total_feedback
            baseline = self._baselines.get(tool_name)
            if baseline:
                result["baseline_calls"] = baseline.call_count
                result["baseline_latency"] = baseline.latency_stats.to_dict()
        return result

    def get_profile(self, tool_name: str) -> Optional[ToolProfile]:
        """Return the profile for tool_name, or None."""
        return self._profiles.get(tool_name)

    # ------------------------------------------------------------------
    # Main verification entry point
    # ------------------------------------------------------------------

    def verify(
        self,
        tool_name: str,
        result: Any,
        execution_time_ms: float,
        *,
        args: Optional[Any] = None,
        user_query: Optional[str] = None,
        session_id: Optional[str] = None,
        call_stack_verified: bool = False,
        # Old-style API compat — response= is an alias for result=
        response: Optional[Any] = None,
    ) -> VerificationResult:
        """Verify a tool call result using the full tiered Bayesian pipeline.

        Args:
            tool_name: Name of the tool that was called.
            result: The value returned by the tool (or use ``response=`` for compat).
            execution_time_ms: Wall-clock time in milliseconds.
            args: Arguments passed to the tool.
            user_query: Original user query (used for semantic similarity check).
            session_id: Session identifier for consistency tracking.
            call_stack_verified: True if call was confirmed via stack inspection.
            response: Alias for ``result`` (backward compatibility).

        Returns:
            :class:`VerificationResult` with verdict, confidence, and signals.
        """
        # Backward compat: accept response= as alias for result=
        if result is None and response is not None:
            result = response

        profile = self._profiles.get(tool_name)
        prior = self._threshold_manager.get_prior(tool_name)

        # ----------------------------------------------------------------
        # TIER 0: Zero-cost checks
        # ----------------------------------------------------------------
        tier_0_signals: dict[str, SignalResult] = {}

        # --- Latency check ---
        if not call_stack_verified:
            latency_range = profile.expected_latency_ms if profile else (2.0, 60_000.0)
            baseline = self._baselines.get(tool_name)
            hist_stats = baseline.latency_stats.to_dict() if baseline and baseline.call_count >= 8 else None
            fired, score, detail = check_latency_anomaly(
                execution_time_ms, latency_range, hist_stats
            )
            # Use dynamic LR: impossibly fast calls (<2ms) get a very high LR
            # because the signal score is near 1.0 and this is near-certain proof
            base_lr = self._get_lr(tool_name, "latency_anomaly")
            if fired and execution_time_ms < 2.0 and score >= 0.9:
                # Sub-2ms for any I/O tool is physically impossible — treat as
                # near-definitive evidence. LR=50 pushes posterior well past
                # the block threshold even as a single signal.
                effective_lr = max(base_lr, 50.0)
            elif fired and execution_time_ms < 2.0:
                # Sub-2ms but not extreme (e.g., 1.5ms) — strong signal
                effective_lr = max(base_lr, 15.0)
            else:
                effective_lr = base_lr
            tier_0_signals["latency_anomaly"] = SignalResult(fired, score, detail, effective_lr)

        # --- Schema compliance ---
        if profile and (profile.required_fields or profile.forbidden_fields):
            fired, score, detail = check_schema_compliance(
                result, profile.required_fields, profile.forbidden_fields
            )
            lr = self._get_lr(tool_name, "schema_mismatch")
            tier_0_signals["schema_mismatch"] = SignalResult(fired, score, detail, lr)

        # --- Pattern matching ---
        if profile and profile.response_patterns:
            fired, score, detail = check_response_patterns(result, profile.response_patterns)
            lr = self._get_lr(tool_name, "pattern_mismatch")
            tier_0_signals["pattern_mismatch"] = SignalResult(fired, score, detail, lr)

        # --- Length bounds ---
        if profile and (profile.min_response_length or profile.max_response_length):
            fired, score, detail = check_response_length(
                result, profile.min_response_length, profile.max_response_length
            )
            lr = self._get_lr(tool_name, "length_anomaly")
            tier_0_signals["length_anomaly"] = SignalResult(fired, score, detail, lr)

        # ----------------------------------------------------------------
        # BAYESIAN COMBINER — Tier 0 update
        # ----------------------------------------------------------------
        posterior = self._bayesian_update(prior, tier_0_signals)

        # ----------------------------------------------------------------
        # Early decision thresholds
        # ----------------------------------------------------------------
        effective_accept = self.accept_threshold
        effective_flag = self._threshold_manager.get_threshold(tool_name)

        # If very high confidence of hallucination after Tier 0, block immediately
        if posterior >= effective_flag:
            signals = tier_0_signals
            verdict = "block"
            explanation = self._build_explanation(signals, posterior, "block")
            self._record_baseline(tool_name, execution_time_ms, result, args)
            return VerificationResult(
                verdict=verdict,
                confidence=round(posterior, 4),
                signals=signals,
                tier_reached=VerificationTier.TIER_0,
                explanation=explanation,
                prior=prior,
                posterior=round(posterior, 4),
            )

        # ----------------------------------------------------------------
        # TIER 1: Post-execution zero-cost checks
        # ----------------------------------------------------------------
        tier_1_signals: dict[str, SignalResult] = {}

        # --- SPC baseline check ---
        baseline = self._get_or_create_baseline(tool_name)
        spc_result = baseline.check_anomaly(execution_time_ms, result)
        if spc_result.is_anomalous:
            desc = "; ".join(a.description for a in spc_result.anomalies[:3])
            lr = self._get_lr(tool_name, "spc_anomaly")
            tier_1_signals["spc_anomaly"] = SignalResult(
                True, spc_result.score, desc, lr
            )

        # --- Session consistency ---
        if session_id:
            session_history = self._consistency_tracker.get_session_history(
                tool_name, session_id
            )
            if session_history:
                consistency_result = self._consistency_tracker.check_session_consistency(
                    tool_name, result, session_id=session_id
                )
                if not consistency_result.is_consistent:
                    desc = "; ".join(v.description for v in consistency_result.violations[:2])
                    lr = self._get_lr(tool_name, "session_inconsistency")
                    tier_1_signals["session_inconsistency"] = SignalResult(
                        True, consistency_result.score, desc, lr
                    )

        # --- Cross-session / historical consistency ---
        if args is not None:
            hist_consistency = self._consistency_tracker.check_historical_consistency(
                tool_name, args, result
            )
            if not hist_consistency.is_consistent:
                desc = "; ".join(v.description for v in hist_consistency.violations[:2])
                lr = self._get_lr(tool_name, "historical_inconsistency")
                tier_1_signals["historical_inconsistency"] = SignalResult(
                    True, hist_consistency.score, desc, lr
                )

        # --- Value plausibility (SPC on numeric fields) ---
        if baseline.call_count >= 8:
            hist_values = {
                k: v.recent_values
                for k, v in baseline.value_ranges.items()
                if v.count >= 8
            }
            fired, score, detail = check_value_plausibility(result, tool_name, hist_values)
            if fired:
                lr = self._get_lr(tool_name, "value_plausibility")
                tier_1_signals["value_plausibility"] = SignalResult(fired, score, detail, lr)

        # --- Optional: semantic similarity (if sentence-transformers available) ---
        if user_query:
            try:
                from agentguard.verification.embeddings import check_semantic_similarity
                fired, score, detail = check_semantic_similarity(
                    user_query, result, tool_name
                )
                if fired:
                    lr = self._get_lr(tool_name, "semantic_similarity_low")
                    tier_1_signals["semantic_similarity_low"] = SignalResult(
                        fired, score, detail, lr
                    )
            except Exception:
                pass  # Embeddings are optional

        # ----------------------------------------------------------------
        # BAYESIAN COMBINER — Tier 1 update
        # ----------------------------------------------------------------
        all_signals = {**tier_0_signals, **tier_1_signals}
        posterior = self._bayesian_update(prior, all_signals)

        # ----------------------------------------------------------------
        # Record to baselines and consistency tracker AFTER all checks
        # ----------------------------------------------------------------
        self._record_baseline(tool_name, execution_time_ms, result, args)
        self._consistency_tracker.record(tool_name, args, result, session_id=session_id)

        # ----------------------------------------------------------------
        # Final verdict
        # ----------------------------------------------------------------
        if posterior >= effective_flag:
            verdict = "block"
            tier = VerificationTier.TIER_1
        elif posterior >= effective_accept:
            verdict = "flag"
            tier = VerificationTier.TIER_1
        else:
            verdict = "accept"
            tier = VerificationTier.TIER_1 if tier_1_signals else VerificationTier.TIER_0

        explanation = self._build_explanation(all_signals, posterior, verdict)
        return VerificationResult(
            verdict=verdict,
            confidence=round(posterior, 4),
            signals=all_signals,
            tier_reached=tier,
            explanation=explanation,
            prior=prior,
            posterior=round(posterior, 4),
        )

    # ------------------------------------------------------------------
    # Bayesian combiner (log-odds form)
    # ------------------------------------------------------------------

    def _bayesian_update(
        self,
        prior: float,
        signals: dict[str, SignalResult],
    ) -> float:
        """Compute P(H | signals) using log-odds Bayesian update.

        Uses log-odds form for numerical stability, as recommended in
        Section 4.2 of the research.

        Args:
            prior: Prior P(hallucination).
            signals: Dict of signal name → SignalResult.

        Returns:
            Posterior P(hallucination).
        """
        # Clamp prior away from 0 and 1 for log-odds stability
        prior = max(1e-6, min(1.0 - 1e-6, prior))
        log_odds = math.log(prior / (1.0 - prior))

        for signal_name, signal_result in signals.items():
            lr = signal_result.likelihood_ratio

            if signal_result.fired:
                # Signal fired: update toward hallucination
                # Scale by signal score to weight strong signals more
                effective_lr = 1.0 + (lr - 1.0) * signal_result.score
                effective_lr = max(1.0, effective_lr)  # don't go below 1
                log_odds += math.log(effective_lr)
            else:
                # Signal absent: slight update toward no hallucination
                # P(not fire | hall) ≈ 0.1 * LR scaling
                absent_lr = 1.0 / max(lr * 0.1, 1.01)
                log_odds += math.log(absent_lr)

        # Convert back to probability
        odds = math.exp(log_odds)
        posterior = odds / (1.0 + odds)
        return max(0.0, min(1.0, posterior))

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_lr(self, tool_name: str, signal_name: str) -> float:
        """Return likelihood ratio for a signal, with per-tool override."""
        # Check for per-tool adaptive override
        lr = self._threshold_manager.get_likelihood_ratio(tool_name, signal_name)
        if lr is not None:
            return lr
        return GLOBAL_LIKELIHOOD_RATIOS.get(signal_name, 2.0)

    def _get_or_create_baseline(self, tool_name: str) -> ToolBaseline:
        """Return existing baseline or create a new one."""
        if tool_name not in self._baselines:
            self._baselines[tool_name] = ToolBaseline(tool_name)
        return self._baselines[tool_name]

    def _record_baseline(
        self,
        tool_name: str,
        execution_time_ms: float,
        result: Any,
        args: Any,
    ) -> None:
        """Record execution data to the baseline (for future SPC checks)."""
        baseline = self._get_or_create_baseline(tool_name)
        baseline.record(execution_time_ms, result, args)

    def _build_explanation(
        self,
        signals: dict[str, SignalResult],
        posterior: float,
        verdict: str,
    ) -> str:
        """Build a human-readable explanation of the verification result."""
        fired = [
            f"{name}: {s.detail}"
            for name, s in signals.items()
            if s.fired and s.detail
        ]
        if not fired:
            return (
                f"All signals within expected range. "
                f"P(hallucination)={posterior:.3f} → {verdict}"
            )
        summary = f"P(hallucination)={posterior:.3f} → {verdict}. "
        summary += "Signals fired: " + "; | ".join(fired[:5])
        return summary

    # ------------------------------------------------------------------
    # Feedback interface
    # ------------------------------------------------------------------

    def record_feedback(
        self,
        tool_name: str,
        confidence_score: float,
        was_hallucination: bool,
    ) -> None:
        """Record feedback to update adaptive thresholds and likelihood ratios.

        Args:
            tool_name: Name of the tool the feedback is for.
            confidence_score: The confidence score produced for this call.
            was_hallucination: True if the call was actually hallucinated.
        """
        self._threshold_manager.record_feedback(
            tool_name, confidence_score, was_hallucination
        )

    # ------------------------------------------------------------------
    # Old-style verify signature for backward compatibility
    # ------------------------------------------------------------------

    def verify_legacy(
        self,
        tool_name: str,
        execution_time_ms: float,
        response: Any,
        *,
        call_stack_verified: bool = False,
    ) -> "VerificationResult":
        """Backward-compatible verify signature matching old HallucinationDetector.

        Args:
            tool_name: Tool name.
            execution_time_ms: Execution time in ms.
            response: The tool response.
            call_stack_verified: If True, skip latency check.

        Returns:
            :class:`VerificationResult`.
        """
        return self.verify(
            tool_name=tool_name,
            result=response,
            execution_time_ms=execution_time_ms,
            call_stack_verified=call_stack_verified,
        )
